### ISSUE TITLE
No Arabic support in # patterns

### ISSUE THREAD

**Issue by marcinjakubowski** [ray007/simple_dt.js#5]
When # pattern is used, support for time in Arabic is gone. The following:

```
const sdf = new SimpleDateFormat('ar-SA')
console.log('with #', sdf.format('# hh:mm', new Date()))
console.log('without #', sdf.format('hh:mm', new Date()))
```

Produces:

with #
 07:
without #
٠٧:٥٣

**Comment by ray007** [comment]
Checked in a few fixes for locales with non-latin scripts (e.g. arabic) and published version `0.2.0`.
